[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "warp"
version = "0.0.1"
dependencies = []
requires-python = ">=3.10"
authors = [
  {name = "Saul Nunez", email = "saul.nunez99@gmail.com"},
]
readme = "README.md"